#! /usr/bin/env bash

# clean output dir
rm -rf pb/*

# create output dir if not exists
mkdir -p pb

for proto_file in $(find "./proto/" -name "*.proto"); do
  protoc -I proto --grpc-gateway_out ./pb \
    --grpc-gateway_opt logtostderr=true \
    --grpc-gateway_opt paths=source_relative \
    --proto_path=./proto \
    --go_out=./pb --go_opt=paths=source_relative \
    --go-grpc_out=./pb --go-grpc_opt=paths=source_relative \
    --validate_out="lang=go:./pb" --validate_opt=paths=source_relative \
    "$proto_file"
done
